config/routes.rb
Rails.application.routes.draw do
  root to: 'application#home'

  get "about_page", to: "application#about_page"
  get "static_page", to: "application#static_page"
  get "another_page", to: "application#another_page"

  resources :lists, only: %i[index show create new destroy] do
    resources :bookmarks, only: %i[new create]
    resources :reviews, only: %i[new create]
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }

end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true


  # ..............................................

  include PgSearch::Model
  pg_search_scope :search_by_name,
    against: [:name],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

    # ..................................................
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list

  validates :description, presence: true, length: {minimum: 10}
  validates :rating, presence: true, numericality: {only_integer: true, greater_than: 0, less_than_or_equal_to: 10}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def about_page
  end

  def static_page
  end

  def another_page
  end

  def home
    @skip_navbar = true
  end

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.create(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(params[:list_id])
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end


  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :list_id, :movie_id)
  end



  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    if params[:query].present?
      @lists = List.search_by_name(params[:query])
    else
      @lists = List.all
    end
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @review = Review.new(list: @list)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo, :description)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @list = List.find(params[:list_id])
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

private

  def review_params
    params.require(:review).permit(:description, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/application/about_page.html.erb
<h1> this is the about page </h1>

<%= link_to "See all lists", lists_path, class: 'btn btn-primary' %>

app/views/application/another_page.html.erb
<h1> this is another page </h1>

<%= link_to "See all lists", lists_path, class: 'btn btn-primary' %>

app/views/application/home.html.erb
 <%= link_to lists_path do %>
  <div class="home-page-container">
    <div class= "home_page_2">
      <div class="home_content">
        <h2> Welcome to Ruperts Movie Saving App <h2>

        <h3> please click to enter <h3>
      </div>
    </div>
  </div>
<% end %>

app/views/application/static_page.html.erb
<h1> this is the static page </h1>

<%= link_to "See all lists", lists_path, class: 'btn btn-primary' %>

app/views/bookmarks/_modal.html.erb
<div class="modal fade" id="new_movie_modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add a movie to your <%= list.name %> list</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
        </button>
      </div>

      <%= simple_form_for [list, bookmark] do |f| %>
        <div class="modal-body">
          <%= f.association :movie, collection: Movie.all.order(:title), prompt: "Select a movie", input_html: { data: { controller: "tom-select" } } %>
          <%= f.input :comment, placeholder: "Enter a comment about the movie" %>
        </div>
        <div class="modal-footer">
          <%= f.submit "Add movie", class: "btn btn-flat" %>
          <button type="button" class="btn btn-cancel" data-bs-dismiss="modal">Back</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookmarks/new.html.erb
<div class="bookmark_new">
    <div class="add_movie">
      <h3 class="bookmark_center">Please add a movie to the <%= @list.name %> list</h3>
      <%= simple_form_for [@list, @bookmark] do |f| %>
        <%= f.association :movie, prompt: "Select a movie", input_html: {data: { controller: "tom-select"}} %>
        <%= f.input :comment, placeholder: 'Enter a comment about the movie', class: "bookmark_comment" %>
        <%= f.submit 'Add move to list', class: "nav_button_bookmark" %>
      <% end %>
    </div>
</div>
<div class="return_button">
  <%= link_to "Return to list", list_path(@list), class: 'nav_button' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
   <script src="https://kit.fontawesome.com/fc11b98403.js" crossorigin="anonymous"></script>
   <style>
@import url('https://fonts.googleapis.com/css2?family=Montserrat&display=swap');
</style>
  </head>

  <% unless @skip_navbar %>

      <div class="banner" style="background-image: url('https://hips.hearstapps.com/thepioneerwoman/wp-content/uploads/2018/05/types-of-popcorn-boxes-2.jpg?resize=1200:*');">
        <div class="container">
          <div class= "banner-header">
            <h1>Welcome to Rupert's<strong> movie saving</strong> app!</h1>
            <p>Organise your movie collection with next level efficinecy</p>
          </div>
        </div>
      </div>

  <% end %>



  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="list_header">
     <div class="list_header_content">

     <h1> Please search from our lists below <h1>

        <%= form_with url: lists_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find a list"
              %>
            <%= submit_tag "Search", class: "btn btn-primary" %>
        <% end %>
     </div>
   </div>

      <div class= "lists_title">
        <h1>All lists<h1>
        <p> Please click on a list below to find your movie sugggestions! <p>
      </div>

  <div class="list_card_container">
      <div class="list_cards">
          <% @lists.each do |list| %>
            <div class="index_card">
              <%= link_to list_path(list) do %>
                   <% if list.photo.attached? %>
                     <%= cl_image_tag list.photo.key, height: 400, width: 400, crop: :fill %>
                   <% else %>
                     <%= image_tag("error.png", height: '400', width: '400') %>
                   <% end %>
                <div class="index_card_info">
                  <div class="index_card_name">
                    <h1> <%= list.name %> <h1>
                  </div>
                  <div class="index_card_description">
                    <h2><%= list.description  %> <h2>
                  </div>
                  <p> <%= link_to '<i class="fa-solid fa-trash"></i>'.html_safe , list, method: "delete", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{list.name}"} %> </p>
                </div>
               <% end %>
               </div>
          <% end %>
     </div>
  </div>
<div class = "new_list_button">
  <%= link_to "Add a new list", new_list_path, class: 'nav_button' %>
</div>
  <div class="index_footer">

    <div class="index_footer_buttons">

      <%= link_to "About", about_page_path, class: 'nav_button' %>
      <%= link_to "Static Test", static_page_path, class: 'nav_button' %>
      <%= link_to "Another Page", another_page_path, class: 'nav_button' %>
    </div>
</div>

app/views/lists/new.html.erb
<div class="list_new">
  <div class="add_list">
    <h1 class= "list_center">Create a new list</h1>
    <%= simple_form_for @list do |f| %>
      <%= f.input :name, :label => 'Please enter your list name', :placeholder => 'List name' %>
      <%= f.input :description, :label => 'Please add a list description', :placeholder => 'List description' %>
      <%= f.input :photo, as: :file %>
      <%= f.submit class: 'nav_button_bookmark' %>
    <% end %>

  </div>

</div>
<%= link_to "Back to lists", lists_path, class: 'nav_button_bookmark' %>

app/views/lists/show.html.erb
<div class= "list-name">
  <h1>You are viewing <%= @list.name %> <h1>
</div>



<div class="list_show_image">
  <% if @list.photo.attached? %>
    <%= cl_image_tag @list.photo.key, height: 400, width: 400, crop: :fill %>
  <% else %>
    <%= image_tag("error.png", height: '400', width: '400') %>
  <% end %>
</div>

<div class="add-button">
  <%= link_to "Add a film to the list", new_list_bookmark_path(@list), class: 'nav_button' %>
  <%= link_to "Add a review to the list", new_list_review_path(@list), class: 'nav_button' %>
</div>

<div class="film_list">
  <ol style="list-style-type: upper-roman;">
   <h2> Films in the list  <h2>
    <% @list.movies.each do |movie| %>
     <li>
        <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
      <div class="card-product-wrapper">
      <h2><%= movie.title %></h2>
        <div class="card-product">

          <%= image_tag movie.poster_url , size: "120x120", class: "card-product-img"%>
            <div class="card-product-infos">

              <h3><strong>Synopsys: </strong> <%= movie.overview%></h3>
              <h4><strong>My comment: </strong> <%=bookmark.comment%><h4>
              <h4><strong>Average rating: </strong> <%=movie.rating%><h4>
            <p> <%= link_to '<i class="fa-solid fa-trash"></i>'.html_safe , bookmark, method: "delete", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{movie.title} from your #{@list.name} list"} %> </p>
            </div>
        </div>
      </div>
      <% end %>
      </li>
    </ol>
</div>

<div class="review_list">
<ul >
<h3>List Reviews <h3>
      <% @list.reviews.each do |review| %>
          <div class="card-product-review ">
              <div>
                <p>List Review: <%= review.description%></p>
                <p>Rating: <%=review.rating%><p>
              </div>
          </div>
      <% end %>
    </ul>
    </div>

<div class="return_button">
  <%= link_to "Return to list menu", lists_path, class: 'nav_button' %>
</div>

app/views/reviews/new.html.erb
<div class="review_new">
    <div class="add_review">
      <h3 class="bookmark_center">Please create your review below</h3>
      <% @list = List.find(params[:list_id]) %>
      <%= simple_form_for [@review], url:list_reviews_path(@list), method: :post  do |f| %>
      <%# <%= simple_form_for [@list, @review] do |f| %>
        <%= f.input :rating, placeholder: 'Please enter your rating 1-10' %>
        <%= f.input :description, :label => 'Your thoughts about the list', placeholder: 'Enter your thoughts about the list' %>
        <%= f.submit class: "nav_button_bookmark" %>
      <% end %>
    </div>
</div>
<div class="return_button">
  <%= link_to "Return to list", list_path(@list), class: 'nav_button' %>
</div>